# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: node-sql-parser package to npm and gpr

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Temp disable SSL Verification for registry.npm.taobao.org
        run: npm config set strict-ssl false

      - run: npm install
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Temp disable SSL Verification for registry.npm.taobao.org
        run: npm config set strict-ssl false

      - run: npm install

      - name: Reenable SSL Verification for registry.npm.taobao.org
        run: npm config set strict-ssl true

      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM_TOKEN}}
      - run: cd output/prod && npm publish

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@taozhi8833998'

      - name: Temp disable SSL Verification for registry.npm.taobao.org
        run: npm config set strict-ssl false

      - run: npm install

      - name: Reenable SSL Verification for registry.npm.taobao.org
        run: npm config set strict-ssl true

      - name: Update package.json name
        run: sed -i '2,2s/node-sql-parser/@taozhi8833998\/node-sql-parser/g' package.json
      - run: echo registry=https://npm.pkg.github.com/taozhi8833998 >> .npmrc
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}
      - run: cd output/prod && npm publish
